### ISSUE TITLE
No se puede completar un checkout exitoso en Magento 2.3

### ISSUE THREAD

**Issue by dsueiro** [TransbankDevelopers/transbank-plugin-magento2-webpay#24]
Al realizar un checkout en el ambiente de prueba con la última versión del módulo instalado sobre Magento 2.3 y volver a Magento luego de marcar el pago como aceptado:

- Redirige a la home del sitio
- Muestra un error "INVALID FORM KEY. PLEASE REFRESH THE PAGE."
- El carrito sigue cargado

**Comment by a1b4** [comment]
@dsueiro Hola, puedes indicarnos si has podido resolver este problema.
y si no has podido solucionarlo puedes indicarnos la versión del plugin y de php que estás utilizando.

saludos.

**Comment by dsueiro** [comment]
Conseguí solucionarlo extendiendo este plugin con un módulo custom. La solución estaría basada en este artículo https://magento.stackexchange.com/questions/253414/magento-2-3-upgrade-breaks-http-post-requests-to-custom-module-endpoint . 

No envié un PR porque la solución que implementé no es backward compatible con Magento 2.2

**Comment by a1b4** [comment]
@dsueiro Muchas gracias por el aporte, puede ser de ayuda para otros integradores.

Saludos.

**Comment by a1b4** [comment]
Hola, la[ ultima versión publicada del plugin ](https://github.com/TransbankDevelopers/transbank-plugin-magento2-webpay/releases/latest)es compatible con la versión 2.3.1 de Magento.

Saludos
