### ISSUE TITLE
Compatibilidad Magento 2.3.1 y PHP 7.2

### ISSUE THREAD

**Issue by panchomuniz** [TransbankDevelopers/transbank-plugin-magento2-webpay#30]
Se queda en bucles infinitos al ser probado con Magento 2.3.1 y con PHP 7.2.16

Por favor ayuda con la compatibilidad

**Comment by Richardmaximun** [comment]
A mi me instaló con composer la version 3.1.5 en M2 2.3.1 pero no se visualiza en el backend. No se puede configurar ni habilitar, nada de nada.

Las ver mas altas de webpay dan errores de compatibilidad con PHP 7.2 y con el framework 102. La version M2 2.3.1 fue para corregir una vulnerabilidad que afectó a mas de 300k de comercios en el mundo por tanto, muchos debemos hacer el update pero si este pluging no se actualiza, estamos hasta el copi. 

Debe ser chileno este repositorio. Para que no te respondan ni 'hola' en 20 dias ... ;)

**Comment by a1b4** [comment]
@panchomuniz Hola, lamentablemente el plugin aun no es compatible con la versión de php 7.2, esperamos poder realizar esta mejora pronto.
Por otro lado, todos los plugin son open source, por lo que si tú has realizando alguna mejora para la compatibilidad te invitamos a crear un Pull Request.

Saludos.

**Comment by RodrigoAyala** [comment]
@Richardmaximun 
> Debe ser chileno este repositorio. Para que no te respondan ni 'hola' en 20 dias ... ;)

Este tipo de comentarios no son aceptados en la comunidad. Puedo entender la frustración por la demora en la respuesta, pero eso no justifica este tipo de comentarios ofensivos.

**Comment by Richardmaximun** [comment]
> @Richardmaximun
> 
> > Debe ser chileno este repositorio. Para que no te respondan ni 'hola' en 20 dias ... ;)
> 
> Este tipo de comentarios no son aceptados en la comunidad. Puedo entender la frustración por la demora en la respuesta, pero eso no justifica este tipo de comentarios ofensivos.

Amigo, "ser chileno" no es ofensivo, es una cualidad; Fijate que me respondes a mí por sentirte aludido y no a @panchomuniz en 20 dias, ni a @dsueiro en 1 mes y medio. Eso es una cualidad ;)

**Comment by RodrigoAyala** [comment]
@Richardmaximun estimado, ruego que agregues comentarios que **se relacionen al issue**, mi comentario hacia ti es un Warning de moderación, sin esperar respuesta a eso. Gracias 👍

**Comment by Richardmaximun** [comment]
> Por otro lado, todos los plugin son open source, por lo que si tú has realizando alguna mejora para la compatibilidad te invitamos a crear un Pull Request.

Hola @a1b4 ,

Estuve dandole una mirada pero cualquier mejora en la compatibilidad depende del SDK, cierto? y el SDK sigue en php 5.5.0.

**Comment by a1b4** [comment]
Hola @Richardmaximun el sdk especifica php >= 5.5.0

Saludos.

**Comment by panchomuniz** [comment]
> @panchomuniz Hola, lamentablemente el plugin aun no es compatible con la versión de php 7.2, esperamos poder realizar esta mejora pronto.
> Por otro lado, todos los plugin son open source, por lo que si tú has realizando alguna mejora para la compatibilidad te invitamos a crear un Pull Request.
> 
> Saludos.

Hola @a1b4 Muchas gracias!

**Comment by Richardmaximun** [comment]
> Hola @Richardmaximun el sdk especifica php >= 5.5.0
> 
> Saludos.

Sí @a1b4 , ya pasó el SDK 1.5.1 

ahora estoy testeando el codigo con los modulos de magento 2.3.1 en php 7.2.x.

**Comment by a1b4** [comment]
@Richardmaximun muchas gracias por el apoyo con las pruebas :)

**Comment by panchomuniz** [comment]
Hola @a1b4 , una duda cuando hagan esta compatibilidad, este ticket lo cerraran o algo asi. En el fondo es para saber como enterarme cuando esto lo vean, 
GRacias

**Comment by rovak73** [comment]
Hola, hay alguna novedad con la compatibilidad de M2.3.1 y PHP7.2?
He tratado de instalar el plugin y me arroja el siguiente error:

1 exception(s):
Exception #0 (Exception): Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/magento2/app/code/Transbank/Webpay/Model/LogHandler.php on line 197

Exception #0 (Exception): Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/magento2/app/code/Transbank/Webpay/Model/LogHandler.php on line 197
<pre>#1 count() called at [app/code/Transbank/Webpay/Model/LogHandler.php:197]
#2 Transbank\Webpay\Model\LogHandler->setLogCount() called at [app/code/Transbank/Webpay/Model/LogHandler.php:295]
#3 Transbank\Webpay\Model\LogHandler->getResume() called at [app/code/Transbank/Webpay/Block/System/Config/TbkButton.php:26]
#4 Transbank\Webpay\Block\System\Config\TbkButton->__construct() called at [lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:116]
#5 Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject() called at [lib/internal/Magento/Framework/ObjectManager/Factory/Compiled.php:108]
#6 Magento\Framework\ObjectManager\Factory\Compiled->create() called at [lib/internal/Magento/Framework/ObjectManager/ObjectManager.php:56]
#7 Magento\Framework\ObjectManager\ObjectManager->create() called at [lib/internal/Magento/Framework/View/Element/BlockFactory.php:46]
#8 Magento\Framework\View\Element\BlockFactory->createBlock() called at [lib/internal/Magento/Framework/View/Layout/Generator/Block.php:268]
#9 Magento\Framework\View\Layout\Generator\Block->getBlockInstance() called at [lib/internal/Magento/Framework/View/Layout/Generator/Block.php:248]
#10 Magento\Framework\View\Layout\Generator\Block->createBlock() called at [lib/internal/Magento/Framework/View/Layout.php:776]
#11 Magento\Framework\View\Layout->_createBlock() called at [lib/internal/Magento/Framework/View/Layout.php:759]
#12 Magento\Framework\View\Layout->createBlock() called at [lib/internal/Magento/Framework/View/Layout.php:989]
#13 Magento\Framework\View\Layout->getBlockSingleton() called at [app/code/Magento/Config/Block/System/Config/Form.php:344]
#14 Magento\Config\Block\System\Config\Form->_initElement() called at [app/code/Magento/Config/Block/System/Config/Form.php:316]
#15 Magento\Config\Block\System\Config\Form->initFields() called at [app/code/Magento/Config/Block/System/Config/Form.php:256]
#16 Magento\Config\Block\System\Config\Form->_initGroup() called at [app/code/Magento/Config/Block/System/Config/Form.php:302]
#17 Magento\Config\Block\System\Config\Form->initFields() called at [app/code/Magento/Config/Block/System/Config/Form.php:256]
#18 Magento\Config\Block\System\Config\Form->_initGroup() called at [app/code/Magento/Config/Block/System/Config/Form.php:302]
#19 Magento\Config\Block\System\Config\Form->initFields() called at [app/code/Magento/Config/Block/System/Config/Form.php:256]
#20 Magento\Config\Block\System\Config\Form->_initGroup() called at [app/code/Magento/Config/Block/System/Config/Form.php:202]
#21 Magento\Config\Block\System\Config\Form->initForm() called at [app/code/Magento/Config/Block/System/Config/Form.php:538]
#22 Magento\Config\Block\System\Config\Form->_beforeToHtml() called at [lib/internal/Magento/Framework/View/Element/AbstractBlock.php:667]
#23 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [lib/internal/Magento/Framework/View/Layout.php:557]
#24 Magento\Framework\View\Layout->_renderBlock() called at [lib/internal/Magento/Framework/View/Layout.php:533]
#25 Magento\Framework\View\Layout->renderNonCachedElement() called at [lib/internal/Magento/Framework/View/Layout.php:488]
#26 Magento\Framework\View\Layout->renderElement() called at [lib/internal/Magento/Framework/View/Element/AbstractBlock.php:508]
#27 Magento\Framework\View\Element\AbstractBlock->getChildHtml() called at [app/code/Magento/Config/view/adminhtml/templates/system/config/edit.phtml:28]
#28 include() called at [lib/internal/Magento/Framework/View/TemplateEngine/Php.php:59]
#29 Magento\Framework\View\TemplateEngine\Php->render() called at [lib/internal/Magento/Framework/View/Element/Template.php:271]
#30 Magento\Framework\View\Element\Template->fetchView() called at [lib/internal/Magento/Framework/View/Element/Template.php:301]
#31 Magento\Framework\View\Element\Template->_toHtml() called at [app/code/Magento/Backend/Block/Template.php:129]
#32 Magento\Backend\Block\Template->_toHtml() called at [lib/internal/Magento/Framework/View/Element/AbstractBlock.php:668]
#33 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [lib/internal/Magento/Framework/View/Layout.php:557]
#34 Magento\Framework\View\Layout->_renderBlock() called at [lib/internal/Magento/Framework/View/Layout.php:533]
#35 Magento\Framework\View\Layout->renderNonCachedElement() called at [lib/internal/Magento/Framework/View/Layout.php:488]
#36 Magento\Framework\View\Layout->renderElement() called at [lib/internal/Magento/Framework/View/Layout.php:585]
#37 Magento\Framework\View\Layout->_renderContainer() called at [lib/internal/Magento/Framework/View/Layout.php:535]
#38 Magento\Framework\View\Layout->renderNonCachedElement() called at [lib/internal/Magento/Framework/View/Layout.php:488]
#39 Magento\Framework\View\Layout->renderElement() called at [lib/internal/Magento/Framework/View/Layout.php:585]
#40 Magento\Framework\View\Layout->_renderContainer() called at [lib/internal/Magento/Framework/View/Layout.php:535]
#41 Magento\Framework\View\Layout->renderNonCachedElement() called at [lib/internal/Magento/Framework/View/Layout.php:488]
#42 Magento\Framework\View\Layout->renderElement() called at [lib/internal/Magento/Framework/View/Layout.php:585]
#43 Magento\Framework\View\Layout->_renderContainer() called at [lib/internal/Magento/Framework/View/Layout.php:535]
#44 Magento\Framework\View\Layout->renderNonCachedElement() called at [lib/internal/Magento/Framework/View/Layout.php:488]
#45 Magento\Framework\View\Layout->renderElement() called at [lib/internal/Magento/Framework/View/Layout.php:585]
#46 Magento\Framework\View\Layout->_renderContainer() called at [lib/internal/Magento/Framework/View/Layout.php:535]
#47 Magento\Framework\View\Layout->renderNonCachedElement() called at [lib/internal/Magento/Framework/View/Layout.php:488]
#48 Magento\Framework\View\Layout->renderElement() called at [lib/internal/Magento/Framework/View/Layout.php:585]
#49 Magento\Framework\View\Layout->_renderContainer() called at [lib/internal/Magento/Framework/View/Layout.php:535]
#50 Magento\Framework\View\Layout->renderNonCachedElement() called at [lib/internal/Magento/Framework/View/Layout.php:488]
#51 Magento\Framework\View\Layout->renderElement() called at [lib/internal/Magento/Framework/View/Layout.php:585]
#52 Magento\Framework\View\Layout->_renderContainer() called at [lib/internal/Magento/Framework/View/Layout.php:535]
#53 Magento\Framework\View\Layout->renderNonCachedElement() called at [lib/internal/Magento/Framework/View/Layout.php:488]
#54 Magento\Framework\View\Layout->renderElement() called at [lib/internal/Magento/Framework/View/Layout.php:585]
#55 Magento\Framework\View\Layout->_renderContainer() called at [lib/internal/Magento/Framework/View/Layout.php:535]
#56 Magento\Framework\View\Layout->renderNonCachedElement() called at [lib/internal/Magento/Framework/View/Layout.php:488]
#57 Magento\Framework\View\Layout->renderElement() called at [lib/internal/Magento/Framework/View/Layout.php:585]
#58 Magento\Framework\View\Layout->_renderContainer() called at [lib/internal/Magento/Framework/View/Layout.php:535]
#59 Magento\Framework\View\Layout->renderNonCachedElement() called at [lib/internal/Magento/Framework/View/Layout.php:488]
#60 Magento\Framework\View\Layout->renderElement() called at [lib/internal/Magento/Framework/View/Layout.php:954]
#61 Magento\Framework\View\Layout->getOutput() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:37]
#62 Magento\Framework\View\Layout\Interceptor->getOutput() called at [lib/internal/Magento/Framework/View/Result/Page.php:258]
#63 Magento\Framework\View\Result\Page->render() called at [lib/internal/Magento/Framework/View/Result/Layout.php:171]
#64 Magento\Framework\View\Result\Layout->renderResult() called at [generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php:24]
#65 Magento\Backend\Model\View\Result\Page\Interceptor->renderResult() called at [lib/internal/Magento/Framework/App/Http.php:140]
#66 Magento\Framework\App\Http->launch() called at [lib/internal/Magento/Framework/App/Bootstrap.php:258]
#67 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:40]
</pre>

**Comment by a1b4** [comment]
Hola, hemos realizado la actualización en dos de los plugin y nos encontramos trabajando en este.

Saludos.

**Comment by a1b4** [comment]
Hola a todos, se ha publicado una nueva versión del plugin compatible con php 7.2 y magento 2.3.1

**Comment by Richardmaximun** [comment]
Gran trabajo @a1b4 y equipo!!
