### ISSUE TITLE
Pago sin validación

### ISSUE THREAD

**Issue by manuelcanepa** [TransbankDevelopers/transbank-plugin-magento2-webpay#33]
En el checkout, al redirigirse al formulario de pago, evita las validaciones y es posible terminar de pagar sin que el usuario acepte los terminos y condiciones.

**Comment by ffiebig** [comment]
Hola @manuelcanepa, muchas gracias por reportar el problema. Vamos a crear una tarjeta en Jira para revisarlo.

De todas maneras puede servirnos que nos des tu versión de Magento y PHP. 
E incluso, si te animas, puedes enviarnos un PR si encuentras como solucionarlo 😁

**Comment by manuelcanepa** [comment]
Magento: 2.3
PHP: 7.1.26

En cuanto al PR, podria hacer un aproach basico para que realice una validacion. Me tope con el problema porque desarrolle un plugin que agrega datos en el additional_data del payload en el placeOrder, pero como el modulo de transbank no pasa por el placeOrder antes de redireccionar a pagar, esos datos no me llegan. Al margen de mi problema especifico (Que no tengo el expertise para definir si es o no el camino correcto), ni siquiera pasa por la validacion. En breve sumo el PR para subsanar, al menos, lo de validar los datos, pero creo que antes de redireccionar, deberia pasar por el placeOrder.

**Comment by ffiebig** [comment]
Ya publicamos los cambios de tu PR en la última versión @manuelcanepa, muchas gracias 🎉 !
