### ISSUE TITLE
Duplicacion de orden

### ISSUE THREAD

**Issue by manuelcanepa** [TransbankDevelopers/transbank-plugin-magento2-webpay#35]
Cuando se dispara el "CreateWebpay", se duplica el pedido. El original pasa a "cancelado" y se utiliza el duplicado para continuar con los pasos, esto genera que por cada pedido que un cliente realice, existan dos identicos, uno cancelado y otro con el estado real.

https://github.com/TransbankDevelopers/transbank-plugin-magento2-webpay/blob/e092319ac5b6482be2e300da80b9171e2f70ef7f/Controller/Transaction/CreateWebpay.php#L48-L70

**Comment by ffiebig** [comment]
Disculpa la tardanza, hemos tenido que priorizar otros temas, de todas manera si sigue siendo un problema y nos puedes ayudar sería genial

**Comment by a1b4** [comment]
Hola, hemos realizado los cambios para prevenir la duplicidad de ordenes de compra al iniciar el pago con Webpay. Las ordenes se duplican solo en caso de ser canceladas por el usuario, ya que los números de ordenes de compra no pueden ser re-utilizados. 
Los cambios se encuentran disponibles en la ultima versión del plugin la [3.2.3](https://github.com/TransbankDevelopers/transbank-plugin-magento2-webpay/releases/latest)
