### ISSUE TITLE
Conflicto de librerias jQuery en el administrador

### ISSUE THREAD

**Issue by jcfilho** [TransbankDevelopers/transbank-plugin-magento2-webpay#44]
Dentro del archivo 
Transbank/Webpay/view/adminhtml/layout/adminhtml_system_config_edit.xml

Estan incluyendo la carga de 2 javascript innecesarios, al adicionar la librería jQuery 3.2.1 esta entrando en conflicto con la librería jQuery que magento carga por defecto.

No es necesario adicionar jQuery nuevamente.
Tampoco es necesario adicionar el bootstrap.

He eliminado los 2 javascript de su modulo y trabaja bien.

` <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js" src_type="url" />
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" src_type="url" />`

Por alguna razón magento 2.2.6 no me esta permitiendo eliminar esos recursos externos.

Podría por favor verificar lo que comento para eliminar la inclusión de esas librerias y no generar esos conflictos? lo comento para las futuras actualizaciones.

![image](https://user-images.githubusercontent.com/1810418/61542463-9acf0280-aa0f-11e9-9269-82246784ffe5.png)

Actualmente el error se da en un magento enterprise 2.2.6 que esto manejando en cloud, dejo la captura para guia, al entrar a la parte de STORE -> Configuration.

**Versiones (por favor agrega aquí la siguiente información):**
- Plugin: 3.1.9
- Magento: 2.2.6
- PHP 7.1

**Comment by a1b4** [comment]
@jcfilho Hola, muchas gracias por la información entregada, como ya has realizando el cambio y comprobado que funciona te invito a enviar un PR con el cambio y aportar al repositorio open source del plugin :)
