### ISSUE TITLE
Órdenes procesadas por Webpay con el status "Canceled" no reintegran cantidades al stock

### ISSUE THREAD

**Issue by lash23** [TransbankDevelopers/transbank-plugin-magento2-webpay#47]
**Describe el bug**

Cuando un cliente emite un pedido y escoge pagar con webpay se descuenta 1 artículo de mi stock mientras se confirma el pago, sin embargo si el pedido es cancelado, bien sea por error en el proceso de pago, cancelado por un administrador tras el abandono de la compra o cancelado intencionalmente por el cliente a través del botón "Anular compra", la orden asociada a este pedido recibe el estado de "Canceled", pero los productos en la orden no vuelven al stock, de modo que se descuentan del inventario aún cuando la orden ha sido cancelada.

De momento se ha probado cancelando manualmente ordenes con métodos de pago Offline y estas si reintegran los productos al stock una vez que se asigna el estado "Canceled"

Una consecuencia de este problema es que si el producto tiene pocas cantidades en stock o el cliente tiene múltiples intentos de compra fallidos, el producto quedará fuera de stock al descontarse múltiples veces, inhabilitando el producto para su compra.

**Comportamiento observado**

1) Se emite un pedido por un Producto X, Cantidad en stock antes del pedido: 1

2) El cliente escoge pagar con Webpay

3) Se crea una orden con el status "Pending", el log de Webpay indica "esperando pago con Webpay", Cantidad en stock en este momento: 0

4) El pedido es cancelado (Por error en el pago, por abandono o a través del botón "Anular compra")

5) La orden recibe el status "Canceled", en ocasiones el log de Webpay indica "responseDescription: Rechazo de transacción", en otras ocasiones no indica nuevos registros.

6) las cantidades en la orden no vuelven al inventario, Cantidad en stock después de cancelar la orden: 0. Producto Fuera de Stock.

**Comportamiento esperado**

6) la cantidad en la orden vuelve al inventario, tras ser cancelado el pedido. Cantidad en stock después de cancelar la orden: 1 (original)

**Capturas de pantalla**

![image](https://user-images.githubusercontent.com/52318779/66149313-d2962100-e5e0-11e9-94c3-74eae4e58027.png)

Copio esta captura de pantalla como información adicional, esta orden fue procesada con webpay y tiene el estado de "Cancelada", sin embargo en la columna "Estado del Artículo" indica "Pedido realizado" (debería indicar "Pedido Cancelado"), así mismo, la columna "Cant." debería idnicar "Cancelado: 1"

El producto de la siguiente imagen también tiene el estado de "Cancelada", pero con otro medio de pago

![image](https://user-images.githubusercontent.com/52318779/66151145-b4322480-e5e4-11e9-8e62-dcf9529419fc.png)

**Versiones (por favor agrega aquí la siguiente información):**
- Plugin: [3.2.3]
- Magento: [2.3.1] y Magento [2.3.2]
- PHP [7.1]

**Comment by a1b4** [comment]
Hola @lash23 estamos revisando este issue, me puedes indicar si tienes algún plugin especial para el manejo de stock?

Saludos.

**Comment by lash23** [comment]
Saludos Alba, un placer.

Con gusto, realmente no utilizo extensión, modulo o plugin alguno para
manejar el stock de las tiendas, ninguno más allá de los instalados por
defecto en magento 2.3.1 y magento 2.3.2.

Si gustan puedo facilitar una lista de los plugins instalados en ambas
versiones de magento, pero adelanto que ninguno relacionado con el manejo
del stock.

Feliz tarde.

**Comment by a1b4** [comment]
hola @lash23 hemos resuelto el issue reportado en la ultima versión publicada del plugin https://github.com/TransbankDevelopers/transbank-plugin-magento2-webpay/releases/tag/3.2.4

Saludos y gracias por reportar el problema.
