### ISSUE TITLE
[InvalidArgumentException] 

### ISSUE THREAD

**Issue by rquirola** [TransbankDevelopers/transbank-plugin-magento2-webpay#61]
Hola, 
En una instalación nueva de Magento2 instalé la versión 3.2.7 y al ejecutar la instalación apareció este error:

```
[InvalidArgumentException]                                                                       
  psr-4 namespaces must end with a namespace separator, 'Transbank\Webpay' does not, use 'Transbank\Webpay\'.     
```

**Para reproducir**

1) Actualizar Composer
2) Ejecutar el comando:  
`composer require transbank/webpay-magento2`

Para solucionar instalé la versión 3.2.5 que funciona normalmente
`composer require transbank/webpay-magento2 "3.2.5"`

**Comment by saengate** [comment]
Hola, gracias por reportarlo. Vamos a revisar.

**Comment by saengate** [comment]
@rquirola hemos generado nuevamente el release y comprobamos que se instalara correctamente. Puedes intentar nuevamente.
