### ISSUE TITLE
Error al confirmar transacción: Token inválido al Anular la compra

### ISSUE THREAD

**Issue by ghost** [TransbankDevelopers/transbank-plugin-magento2-webpay#63]
Devuelve "Error al confirmar transacción: Token inválido", al anular la compra, el boton donde se registra la tarjeta de credito.

Reproducir
1 Pon la orden
2 Anula la transaccion en webpay

- Plugin dev:master
- Magento 2.3.3 y 2.3.1
- PHP 7.1 7.2

LOG
2020-01-23T14:48:32+00:00 INFO (6): initTransaction - amount: 10010, sessionId: 2, buyOrder: 7, txDate: 23-01-2020, txTime: 14:48:32
2020-01-23T14:48:33+00:00 INFO (6): initTransaction - initResult: {"return":null,"token":"e95dabf20222fa024a38cdf05138c28e288315fa2876c10818f425f18f2b6769","url":"https:\/\/webpay3gint.transbank.cl\/webpayserver\/initTransaction"}
2020-01-23T14:48:56+00:00 ERR (3): Error al confirmar transacción: Token inválido

**Comment by rfuental** [comment]
Hola, yo tengo el mismo error, para complementar creo que esta varialble de sesión viene vacío.

$this->checkoutSession->getTokenWs()

**Comment by RobSerrano** [comment]
Como lo resolvieron? Tengo el mismo incidente! Gracias

**Comment by RobSerrano** [comment]
> Hola, yo tengo el mismo error, para complementar creo que esta varialble de sesión viene vacío.
> 
> $this->checkoutSession->getTokenWs()

Me pasa lo mismo. @Thumper85 y @rfuental Como lo resolvieron? Gracias!!

**Comment by saengate** [comment]
@RobSerrano que versión del plugin estas usando? se realizo una actualización para cerrar este caso.

**Comment by RobSerrano** [comment]
Estoy utilizando la 3.3.0

**Comment by saengate** [comment]
@RobSerrano ¿te aparece este mensaje? `Error al confirmar transacción: Transacción cancelada`

**Comment by RobSerrano** [comment]
No, el mensaje es Error al confirmar transacción: Token inválido y la variable $this->checkoutSession->getTokenWs() que fue lo que reporto @rfuental el 28 de Enero

**Comment by RobSerrano** [comment]
La variable $this->checkoutSession->getTokenWs() viene vacia, y por ende no continua el proceso de checkout

**Comment by saengate** [comment]
@RobSerrano me gustaría revisar ese caso en profundidad, puedes unirte a Slack y revisamos por interno  https://transbankdevelopers.slack.com/archives/CD3DPMWG3

**Comment by RobSerrano** [comment]
Oka. Bajo que usuaio te busco?

**Comment by saengate** [comment]
> Oka. Bajo que usuaio te busco?

Saul Galan
