### ISSUE TITLE
Pedido al quedar processing no genera Factura

### ISSUE THREAD

**Issue by panchomuniz** [TransbankDevelopers/transbank-plugin-magento2-webpay#69]
Buenos dias, no se si es un bug real o bien algo que se deba configurar. Pero al hacer pruebas con magento 2.3.4, logro realizar pagos y todo, pero no se genera el invoice. 

Podrian por favor indicar si es algo que pueda configurar, o bien quizas alguna recomendacion para hacer esto de forma automtica.

Una descripción concisa sobre el bug.

**Para reproducir**

1. Hacer una compra con metodo de pago Transbank

**Comportamiento observado**

Pedido queda en processing pero no genera invoice

**Comportamiento esperado**

Al estar processing se debio haber generado un invoice

**Versiones (por favor agrega aquí la siguiente información):**
- Plugin: 3.3.0
- Magento: 2.3.4
- PHP 7.1.20-1+ubuntu18.04.1+deb.sury.org+1

Muchas gracias de antemano

**Comment by saengate** [comment]
@panchomuniz esto probablemente esta relacionado a la versión de PHP que estas usando con magento v2.3.4. Hice pruebas con Webpay y otras formas de pago y en todos los casos no pude ver los pedidos en el Invoice. Cambia la versión a PHP 7.2 e intenta nuevamente.

**Comment by panchomuniz** [comment]
Hola,
no entendi, a ti te genera el invoice al realizar un pedido y pagarlo? Porque ese es el comportamiento normal de magento, debiese generarse un invoice al ocurrir una captura
