### ISSUE TITLE
Error en cuando al volver de transbank (Token inválido)

### ISSUE THREAD

**Issue by gdespirito** [TransbankDevelopers/transbank-plugin-magento2-webpay#72]
**Describe el bug**

Al menos en producción, cuando uno se demora mucho en pagar, Transbank redirige automáticamente de vuelta al comercio, pero al llegar a la url commitwebpay se genera un fallo.

**Para reproducir**

1.- Iniciar transacción
2.- Seleccionar el banco en el formulario de pago
3.- Esperar unos 5 minutos
4.- Webpay redirige y se presenta una excepción de Magento

![image](https://user-images.githubusercontent.com/1103494/78089787-c1b34600-739e-11ea-9f46-e27127d44bab.png)

**Comportamiento esperado**

Debería manejar mejor esa situación

El token llega correctamente por POST, pero por alguna razón getTokenWs() devuelve null. 
![image](https://user-images.githubusercontent.com/1103494/78089943-29699100-739f-11ea-9b6f-097614ca457b.png)

**Comment by lcouget** [comment]
Hola. Me está pasando lo mismo. Hice logging de los datos de checkoutSession en el archivo Controller/Transaction/CommitWebpayM22.php y tanto getLastOrderId() y getTokenWs() vienen vacíos.

**Comment by gdespirito** [comment]
@lcouget ¿sabes bajo que circunstancias te sucede? lo que más nos frena en este momento es no conocer cómo replicar el error.

**Comment by lcouget** [comment]
@gonzunigad nos pasa lo mismo. No podemos replicar el error, solo lo vemos pasar en prod. Estoy investigando si hay alguna limitación relacionada la la sesión de PHP, pero no llegué a nada todavía.
Si llego a algo, lo aviso por acá. Saludos.

**Comment by gdespirito** [comment]
Resuelto en el último release 3.4.0 :)
