### ISSUE TITLE
Descuento no aplicado en pasarela

### ISSUE THREAD

**Issue by sergioadofaci** [TransbankDevelopers/transbank-plugin-magento2-webpay#79]
Carro con descuento no aplicado en pasarela de pago.

Al realizar un pago utilizando un código con límite de 1 uso por cliente, no se refleja al momento de pasar a la pasarela.

**Para reproducir:**

1. Configurar un código con límite de 1 uso (ej. 10% descuento en la primera compra)
2. Crear usuario que cumpla con las condiciones del punto 1.
3. Continuar a checkout, verificar que el descuento se aplique.
4. Al pasar a webpay, el valor sin descuento se ve reflejado.

Realizando las pruebas se observa que solamente pasa cuando se limita a 1 uso el código, al parecer webpay llama al quote y "quema" el descuento, por lo que el grandtotal enviado no contiene el descuento.

El descuento debería ser aplicado al pasar al pago.

**Versiones:**

- Plugin: 3.4.0
- Magento: 2.2.5
- PHP: 7.0

**Comment by ffiebig** [comment]
Disculpa la demora @sergioadofaci vamos a tratar de reproducirlo y solucionarlo

**Comment by pparga** [comment]
Algún update?

**Comment by ludcl** [comment]
Tenemos el mismo problema. ¿Alguna noticia? O alguna pista, para por último revisarlo directamente.

**Comment by ffiebig** [comment]
Lamentablemente no hemos tenido el ancho de banda para tomar esto, voy a ver si puedo incrementar su prioridad para que podamos revisarlo. 

En el intertanto si alguien encuentra más información o una posible solución por favor háganos saber, nos ayuda un montón

**Comment by ffiebig** [comment]
Hola, les cuento que ya está en proceso un pequeño, fix, sería ideal que puedan probarlo una vez haga el release. Pueden verlo si quieren en el PR referenciado

**Comment by ludcl** [comment]
> Lamentablemente no hemos tenido el ancho de banda para tomar esto, voy a ver si puedo incrementar su prioridad para que podamos revisarlo.
> 
> En el intertanto si alguien encuentra más información o una posible solución por favor háganos saber, nos ayuda un montón

A mí me funcionó cambiando la línea 83 del archivo CreateWebpayM22.php

```
- $grandTotal = round($quote->getGrandTotal());
+ $grandTotal = round($order->getGrandTotal());
```

Puede servir como alternativa... aunque probaré con la tuya porque puede que solucione el problema de la pantalla de éxito llegando sin sesión (a "empty cart" en vez de "success"), lo que causar problemas con la medición de ventas por Analytics.
Si no se resuelve, escribiré el Issue y trataré de hacer un PR con una alternativa.

**Comment by ffiebig** [comment]
También hice ese cambio, además moví el momento en que guarda el quote. Porfavor cuentenme como les resulta, la version 3.4.2 va con esos cambios. 

Saludos !
