### ISSUE TITLE
Agregar opción de Estado de nueva Orden

### ISSUE THREAD

**Issue by pparga** [TransbankDevelopers/transbank-plugin-magento2-webpay#80]
**No es un bug, es una idea**

Según el flujo de Magento 2, lo ideal seria que una vez se crea la orden y ya es redirigido a webpay las ordenes queden con estado "pending_payment". Hoy en dia las ordenes quedan como "Pending". La gran diferencia entre estos dos estados es que se puede dejar un cronjob nativo de Magento 2 que cancele las ordenes "pending_payment" después de X minutos, en cambio, si quedan "pending", hay que desarrollar un cronjob que vaya revisando las ordenes y que estas sean canceladas si fueron creadas hace mas de X minutos o simplemente cancelarlas manualmente.

**Para reproducir**

Completar proceso de checkout, esperar redirección hacia transbank (se creara la orden) y luego abandonar la ventana

**Comportamiento observado**

Una nueva orden queda con estado "pending"

**Comportamiento esperado**

Debería estar la posibilidad de que al crear una nueva orden esta quede como "pending_payment" en vez de "pending".

**Capturas de pantalla**

![image](https://user-images.githubusercontent.com/7934982/83665766-dfb54680-a599-11ea-888a-95e7e5f0d1c4.png)

**Versiones (por favor agrega aquí la siguiente información):**
- Plugin: 3.4.1
- Magento: 2.3.4
- PHP 7.2.30

**Comment by ffiebig** [comment]
Está buena la sugerencia, la voy a agregar a nuestro backlog de mejoras 👍
