### ISSUE TITLE
Diferencia entre monto total de orden y monto total autorizado

### ISSUE THREAD

**Issue by lcouget** [TransbankDevelopers/transbank-plugin-magento2-webpay#82]
**Describe el bug**

Se encontraron en varias ordenes diferencias entre el monto total de la orden y el monto total aprobado por transbank. Según lo que se pudo observar, el problema radica en que el valor del campo 'grand_total' de la tabla 'quote' es diferente al valor del campo 'grand_total'  de la tabla 'sales_order' en algunos casos, y dado que el módulo tansbank-webpay obtiene los valores necesarios para crear la transaccion del quote y no de la orden, la transacción queda creada y luego es aprobada con los montos incorrectos.

**Para reproducir**

No tenemos los pasos claros como para poder reproducir el issue relacionado a la diferencia encontrada entre el valor  del campo 'grand_total' del quote con respecto al valor 'grand_total' de la tabla 'sales_order', pero si estos valores estan distintos, el módulo de webpay obtiene el monto a autorizar del quote.

**Comportamiento observado**

El monto a aprobarse es el correspondiente al que quedó en el campo 'grand_total' del quote.

**Comportamiento esperado**

Se espera que el monto a aprobarse corresponda al total de la orden (campo grand_total de la tabla 'sales_order')y no al quote.

**Versiones (por favor agrega aquí la siguiente información):**
- Plugin: 3.4.1
- Magento: 2.3.3-p1 (cloud)
- PHP 7.2

**Comment by barbazul** [comment]
Efectivamente el problema se reproduce, por ejemplo si un módulo incorpora un cargo adicional en el pedido (un custom total).

Normalmente los módulos de pago implementan getCheckoutRedirectUrl para redirigir a una página intermedia donde se realiza el envío del form con la información al gateway (ver ejemplo de Paypal). De esta manera, el pedido se encuentra generado antes de iniciar la comunicación con el gateway.

El módulo de webpay utiliza un mecanismo por el cual "hackea" el flujo del checkout, interviene la confirmación del formulario e inicia su propio flujo en la misma página del checkout, controlado por JS.

El flujo debiera ser el mismo que en el resto de los módulos de pago para asegurar compatibildad con Magento y otras extensiones.

**Comment by ffiebig** [comment]
Hice un pequeño cambio en un PR que está en revisión en el cual saco el total del order y no del quote, no se si eso solucionará el problema pero no perdemos nada con probar

**Comment by ffiebig** [comment]
@lcouget será posible que lo pruebes y me cuentes ? Nos ayudaría un montón
