### ISSUE TITLE
Error al cancelar una compra y volver a comprar.

### ISSUE THREAD

**Issue by igamunozz** [TransbankDevelopers/transbank-plugin-magento2-webpay#85]
Al momento de ir a transbank para proceder a pagar, anular la compra y al momento de querer proceder a comprar nuevamente magento retorna el error "Invalid customer address id" y no puede proceder a pagar. Esto sólo ocurrde con este método de pago.

**Para reproducir**

1. Proceder a pagar.
2. Anular compra y volver al sitio o cancelar compra.
3. Realizar nuevamente proceso de compra
4. En checkout shipping se aprecia error.

**Comportamiento observado**

Al parecer, existe un problema con la validación del user isGuest al momento de querer realizar la compra nuevamente luego de haber cancelado una orden.

**Comportamiento esperado**

Procede con éxito a pagar luego de haber anulado previamente una orden.

**Capturas de pantalla**

![error](https://user-images.githubusercontent.com/68357159/94165059-2e942e00-fe60-11ea-934e-515045632d52.png)

**Versiones (por favor agrega aquí la siguiente información):**
- Plugin: 3.4.2
- Magento: 2.4.0 (CE y CC)
- PHP: 7.4

**Comment by joaquin-becerra** [comment]
Si, pude comprobar el error, el problema esta en que se esta validando si el usuario es guest usando la variable quote.guestEmail en 

 https://github.com/TransbankDevelopers/transbank-plugin-magento2-webpay/blob/master/view/frontend/web/js/view/payment/method-renderer/webpay-method.js#L60

Si esta variable se utiliza, al finalizar la orden el quote se transforma en un quote de un usuario guest, trayendo varios problemas.

Aca hace: 

```
if (quote.guestEmail) {
                                    url += '?guestEmail=' + encodeURIComponent(quote.guestEmail);
                                }
```

El problema con eso es que hay modulos que no inicializan bien la variable quote.guestEmail, por ejemplo el modulo de Amazon amzn/amazon-pay-module en su archivo vendor/amzn/amazon-pay-module/view/frontend/web/js/view/form/element/email.js pone:

```
if (this.email()) {

                if ($.validator.methods['validate-email'].call(this, this.email())) {
                    quote.guestEmail = this.email();
                    checkoutData.setValidatedEmailValue(this.email());
                }
                checkoutData.setInputFieldEmailValue(this.email());
            }

```
Cargando en quote.guestEmail el valor de email (sea o no sea guest)

Para solucionarlo habria que cambiar la validacion a 

```
if (!customer.isLoggedIn()) {
                                url += '?guestEmail=' + encodeURIComponent(quote.guestEmail);
                            }
```

En breve voy a intentar de hacer un PR.

Saludos

**Comment by joaquin-becerra** [comment]
Aca el PR:

 https://github.com/TransbankDevelopers/transbank-plugin-magento2-webpay/pull/89
