### ISSUE TITLE
Redirección después de pago a cart

### ISSUE THREAD

**Issue by pparga** [TransbankDevelopers/transbank-plugin-magento2-webpay#86]
En la mayoria de casos después de haber pagado de forma correcta una orden, webpay redirige a **checkout/cart** en vez de **checkout/onepage/success** 

Una descripción concisa sobre el bug.

**Para reproducir**

1. Instalación vanilla de magento 2.3.4, agregar webpay modo integración 
2. Agregar producto a carro y dirigirse a checkout
3. Usar webpay como forma de pago y completar proceso
4. Una vez pagado con webpay de forma correcta deberia uno ser redireccionado a **checkout/onepage/success**

**Comportamiento observado**

En mayoria de los caso webpay redirige a **checkout/cart** en vez de **checkout/onepage/success**

**Comportamiento esperado**

Siempre debe redireccionar a **checkout/onepage/success**

**Versiones (por favor agrega aquí la siguiente información):**
- Plugin: 3.4.2
- Magento: 2.3.4
- PHP 7.2

**Comment by Rodolfox1** [comment]
> En la mayoria de casos después de haber pagado de forma correcta una orden, webpay redirige a **checkout/cart** en vez de **checkout/onepage/success**
> 
> Una descripción concisa sobre el bug.
> 
> **Para reproducir**
> 
> 1. Instalación vanilla de magento 2.3.4, agregar webpay modo integración
> 2. Agregar producto a carro y dirigirse a checkout
> 3. Usar webpay como forma de pago y completar proceso
> 4. Una vez pagado con webpay de forma correcta deberia uno ser redireccionado a **checkout/onepage/success**
> 
> **Comportamiento observado**
> 
> En mayoria de los caso webpay redirige a **checkout/cart** en vez de **checkout/onepage/success**
> 
> **Comportamiento esperado**
> 
> Siempre debe redireccionar a **checkout/onepage/success**
> 
> **Versiones (por favor agrega aquí la siguiente información):**
> 
> * Plugin: 3.4.2
> * Magento: 2.3.4
> * PHP 7.2

Estimado pparga, será que lograste encontrar una solución a este error?

**Comment by pparga** [comment]
Hola @Rodolfox1,

Sí, instalamos este modulo (https://github.com/Veriteworks/CookieFix) que soluciona el error. El bug es por una actualización que hizo Chrome sobre las cookies y afecta a Magento en la mayoría de versiones que he revisado. Ojala te sirva!

**Comment by gdespirito** [comment]
Hola. ¿Estó seguirá pasando en el nuevo plugin REST? https://github.com/TransbankDevelopers/transbank-plugin-magento2-webpay-rest.
