### ISSUE TITLE
Error 500 en página de éxito y correo automático no muestra el método de pago por Webpay Plus

### ISSUE THREAD

**Issue by faldanar** [TransbankDevelopers/transbank-plugin-magento2-webpay#90]
Hola! 
El ambiente actual es:
Servidor: Linux y php 7.3
Magento 2: Versión 2.3.5-p2 en modo developer

El módulo se encuentra actualmente en modo producción y se realizan pagos sin problemas, el tema es que en el correo de confirmación de la compra que le llega al cliente no aparece Webpay Plus en el apartado que dice métodos de pago. Con las otras formas de pago si aparece y sin problemas.

Lo otro es que al realizar el pago y al volver al sitio se arroja error 500 donde debiese aparecer la página de exito. Si hago refresh aparece la página de exito con el resumen de la compra.

Ni idea que puede pasar pero me imagino que es algo del módulo en si... no soy técnico e integrado el sitio 100% yo hasta ahora....

Lo otro aparte es que e intentado poner el sitio en modo producción a traves de SSH y una vez realizo todos los pasos correspondientes, el frontend y backend como que no funcionara el css y .js ....entonces visualmente se ve cualquier cosa. 

La verdad es que ya he avanzado bastante hasta acá y el sitio esta arriba con 2.500 productos pero me estoy quedando atrás con esto.. Alguien por acá que me pueda prestar servicios profesionales para solucionar estos 3 temas... estoy en Santiago.

Saludos,

**Comment by gdespirito** [comment]
Hola! ¿Esto seguirá pasándote en el nuevo plugin REST? Si es así, ideal que nos puedas ayudar replciarndo el issue en ese repo. https://github.com/TransbankDevelopers/transbank-plugin-magento2-webpay-rest

Este plugin ya no recibirá mejoras. Solo el REST :)
