### ISSUE TITLE
Modo INTEGRACIÓN no funciona

### ISSUE THREAD

**Issue by federicoeste** [TransbankDevelopers/transbank-plugin-magento2-webpay#93]
Desde hace algunas semanas, el modo integración no funciona. Al intentar realizar un pago se genera un alert con el error 
"Error al crear transacción".

La opción "Verificar Conexión" que se encuentra en store -> configuration -> sales -> payment methods -> Web Pay -> Parámetros principales -> Herramienta de diagnóstico arroja el error que adjunto en captura.

![webpayissue](https://user-images.githubusercontent.com/80471669/135121913-56842a5c-0f9e-43af-b4a1-9c566c58d018.png)

Esto sucede en Magento 2.3.0 con php7.2

**Comment by oscarHurtadoPrecision** [comment]
tengo exactamente este mismo problema

 
![imagen](https://user-images.githubusercontent.com/91140936/135517413-4b515b90-a12e-40ce-bfc1-e3923da7a781.png)

**Comment by federicoeste** [comment]
@oscarHurtadoPrecision te copio la info que me mandaron desde webpay

 " le informamos que no hay ambiente de integración para plugin en SOAP, ya que es un producto descontinuado y los certificados en este ambiente están obsoletos, le recomendamos actualizar su implementación con Magento a la nueva Api REST, puede encontrar la documentación en el siguiente enlace https://www.transbankdevelopers.cl/plugin/magento/"

**Comment by oscarHurtadoPrecision** [comment]
@federicoeste muchas gracias por tu respuesta te pasaste
